# site settings
title: NKT
subtitle: Nguyen Khoi Tran
email: nguyen.tran@adelaide.edu.au
description: Personal Website and Blog of Nguyen Khoi Tran<br /> Researcher, Reader, Writer.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Santos, The University of Adelaide
city: Adelaide
state: SA
zip_code: 5005
country: Australia
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/nguyentran0212
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/nguyen-khoi-tran-bba22471/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/GenTran91

# build settings
markdown: kramdown

sass:
  style: compressed
